Add a showcase
lomirus/cv-template pull request #5
Opened 2024-04-02 14:38 UTC by uai-uai

Add a showcase

2024-04-02 14:41 UTC, lomirus requested changes

2024-04-02 14:41 UTC, lomirus commented on README.md
> +![](docs/example-with-avatar.jpg)
两张大图占空间过大，可以考虑使用 table（https://github.com/lomirus/gtk-qq）或者 summary 语法优化

2024-04-04 03:10 UTC, uai-uai commented on README.md
> +![](docs/example-with-avatar.jpg)
done

2024-04-04 04:35 UTC, lomirus requested changes
"showcase with/without avatar" 作为表头应当每个单词首字母大写

2024-04-04 05:05 UTC, merged